# Generated by Django 4.2.10 on 2024-04-19 10:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0010_remove_user_test_field'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='test_field',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
    ]
