# Generated by Django 4.2.10 on 2024-04-19 10:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0011_user_test_field'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='test_field',
        ),
    ]
