# Generated by Django 4.2.10 on 2024-04-19 10:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0013_user_staff'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='is_admin',
        ),
    ]
